import { QuartzComponent, QuartzComponentProps } from "./types"
import styles from "./styles.scss"

/**
 * Tag discovery cloud: shows the most-used tags across the site as chips.
 * Clicking a chip opens that tag's listing page (generated by tag-page).
 */

const MAX_TAGS = 12

function pathToRoot(slug: string): string {
  if (!slug || slug === "index") return ""
  const depth = slug.split("/").filter((s) => s.length > 0).length
  return depth <= 1 ? "" : "../".repeat(depth - 1)
}

interface FileEntry {
  slug?: string
  frontmatter?: { tags?: string[] | string }
}

export const TagCloud: QuartzComponent = ({ allFiles, fileData }: QuartzComponentProps) => {
  const files: FileEntry[] = Array.isArray(allFiles) ? allFiles : []
  const counts = new Map<string, number>()

  for (const f of files) {
    const raw = f?.frontmatter?.tags
    const tags = Array.isArray(raw) ? raw : typeof raw === "string" ? raw.split(/,\s*/) : []
    for (const t of tags) {
      const tag = String(t).trim()
      if (tag) counts.set(tag, (counts.get(tag) ?? 0) + 1)
    }
  }

  if (counts.size === 0) return <></>

  const sorted = [...counts.entries()]
    .map(([tag, count]) => ({ tag, count }))
    .sort((a, b) => b.count - a.count || a.tag.localeCompare(b.tag))
    .slice(0, MAX_TAGS)

  const root = pathToRoot(fileData?.slug ?? "index")

  return (
    <div class="tag-cloud">
      <h3 class="tag-cloud-heading">Discover by tag</h3>
      <ul class="tag-cloud-list">
        {sorted.map(({ tag, count }) => (
          <li>
            <a class="tag-cloud-chip" href={`${root}tags/${encodeURIComponent(tag)}`}>
              #{tag}
              <span class="tag-cloud-count">{count}</span>
            </a>
          </li>
        ))}
      </ul>
    </div>
  )
}

TagCloud.css = styles
export default TagCloud

